name: Build and Deploy React Native Expo App

on:
  push:
    branches: [ main ]  # Trigger the workflow on push events to the main branch


jobs:
  build:
    runs-on: ubuntu-latest  # The type of runner that the job will run on

    steps:
    - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Install Dependencies
      run: |
        npm install -g expo-cli
        npm install

    - name: Login to Expo CLI
      env:
        EXPO_CLI_USERNAME: ${{ secrets.EXPO_CLI_USERNAME }}
        EXPO_CLI_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
      run: expo login --non-interactive --username $EXPO_CLI_USERNAME --password $EXPO_CLI_PASSWORD

    - name: Build Project with Expo
      run: eas build -p android --non-interactive

    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: app
        path: ./apk 
    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./apk 
